fix(ci): update West working directory
Previously the workflow only works if `config_path` is a single
directory. If we use something different, e.g., `config_path:
"dot_config/zmk/config"`, West fails with

```
Run west init -l "/__w/dotfiles/dotfiles/dot_config/corne-zmk/config"
  west init -l "/__w/dotfiles/dotfiles/dot_config/corne-zmk/config"
  shell: sh -e {0}
  env:
    build_dir: /tmp/tmp.a9rTeptW6V
    base_dir: /__w/dotfiles/dotfiles
    zephyr_version: 4.1.0
    extra_west_args:
    extra_cmake_args: -DSHIELD="corne_right nice_view_adapter nice_view"
    display_name: corne_right nice_view_adapter nice_view - nice_nano_v2
    artifact_name: corne_right nice_view_adapter nice_view-nice_nano_v2-zmk
=== Initializing from existing manifest repository config
--- Creating /__w/dotfiles/dotfiles/dot_config/corne-zmk/.west and local configuration file
=== Initialized. Now run "west update" inside /__w/dotfiles/dotfiles/dot_config/corne-zmk.

Run west update --fetch-opt=--filter=tree:0
FATAL ERROR: no west workspace found from "/__w/dotfiles/dotfiles"; "west update" requires one.
Things to try:
  - Change directory to somewhere inside a west workspace and retry.
  - Set ZEPHYR_BASE to a zephyr repository path in a west workspace.
  - Run "west init" to set up a workspace here.
  - Run "west init -h" for additional information.
```

This commit fixes the issue by introducing `west_working_directory` that
points to the dirname of `config_path`.